Update troubleshooting-nfs-storage-issues.md
oVirt/ovirt-site pull request #2433
Opened 2021-01-27 23:47 UTC by mattsn0w

Changes proposed in this pull request:

- Added specific configuration for Ubuntu 19.x/20.x NFS servers

- Additional NFS troubleshooting steps and checks.

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @mattsn0w 

This pull request needs review by: (please @mention the reviewer if relevant)

2021-01-28 17:09 UTC, sandrobonazzola commented
Thanks for the contribution! @nirs can you please review?

2021-01-29 00:12 UTC, nirs requested changes
Thanks!

2021-01-29 00:12 UTC, nirs commented on source/develop/troubleshooting-nfs-storage-issues.md
> +* sanlock.log
This is very important!

We can add more info about the logs:
- /var/log/vdsm/supervdsm.log - show mount errors
- /var/log/vdsm/vdsm.log - show error when vdsm try modify the mounted export as user vdsm
- /var/log/sanlock.log - show errors when sanlock try to modify the mounted export as user sanlock

2021-01-29 00:12 UTC, nirs commented on source/develop/troubleshooting-nfs-storage-issues.md
> +# Workarounds for known issues
There should be only one heading level 1:

    # Heading level 1

This should be heading level 2, change is not needed.

2021-01-29 00:12 UTC, nirs commented on source/develop/troubleshooting-nfs-storage-issues.md
> +## NFS Lockups
Same, change not needed

2021-05-05 11:23 UTC, sandrobonazzola commented
This PR also needs to be rebased

2021-05-17 15:00 UTC, sandrobonazzola commented
closing due to inactivity, please reopen if you start working again on this PR

2021-06-02 00:06 UTC, nirs commented
There is important info here that we need to add.

2021-06-03 13:23 UTC, sandrobonazzola commented
@nirs are you handling this?

2022-06-07 06:41 UTC, ahadas commented
@nirs I'm closing this one because there's no progress for a while but please feel free to post an update/updated PR if you think it is worth it

2022-06-07 06:41 UTC, closed without merging