BZ#2010362 - Update order of Grafana Dashboard description
oVirt/ovirt-site pull request #2618
Opened 2021-10-28 14:49 UTC by emarcusRH

Fixes issue [BZ#2010362](https://bugzilla.redhat.com/show_bug.cgi?id=2010362)
 RHV 4.4.9-1 or later
Changes proposed in this pull request:
- Update the sequential order of elements in each Grafana dashboard
in Administration Guide > Monitoring and observability > Grafana Dashboards

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @emarcusRH )

This pull request needs review by:

2021-11-23 21:52 UTC, avlitman approved these changes

2021-11-23 22:13 UTC, avlitman approved these changes
/lgtm

2021-11-24 07:55 UTC, stoobie requested changes
One tiny change requested.

2021-11-24 07:55 UTC, stoobie commented on source/documentation/administration_guide/topics/Grafana_dashboards.adoc
> +    * System dashboard - resource usage and up-time for hosts and storage domains in the system, according to in the latest configurations.
```suggestion
    * System dashboard - resource usage and up-time for hosts and storage domains in the system, according to the latest configurations.
```

2021-11-24 08:17 UTC, avlitman commented on source/documentation/administration_guide/topics/Grafana_dashboards.adoc
> +    * System dashboard - resource usage and up-time for hosts and storage domains in the system, according to in the latest configurations.
+1

2021-11-24 16:43 UTC, sandrobonazzola approved these changes

2021-11-25 10:27 UTC, stoobie approved these changes
LGTM

2021-11-25 12:11 UTC, merged