BZ#1900889 and BZ# 1901149  Updates to VMM guide and Admin guide VM migration options
oVirt/ovirt-site pull request #2676
Opened 2021-12-29 14:44 UTC by emarcusRH

…tions in Host tab

Fixes issue #1900889 and # 1901149

Changes proposed in this pull request:

- Update VMM guide and Admin guide to remove "custom migration downtime" and "auto converge migration" options, and add "enable migration encryption" option
- Update VMM guide and Admin guide to add/reorganize CPU options

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @emarcusRH )

This pull request needs review by: (please @RichardHoch )

2022-01-05 19:07 UTC, dcdacosta commented on source/documentation/administration_guide/topics/Virtual_Machine_Pool_Host_settings_explained.adoc
> +|When selected, this virtual machine can only be migrated to a host with the same TSC frequency. THis option is only valid for High Performance virtual machines.
Change to lower case h in "THis option".

2022-01-05 19:15 UTC, dcdacosta commented on source/documentation/administration_guide/topics/Virtual_Machine_Pool_Host_settings_explained.adoc
> +If the network connection breaks prior to the completion of the post-copy process, the {engine-name} pauses and then kills the running VM. Do not use post-copy migration if the VM availability is cri
Suggest changing VM to virtual machine.

2022-01-05 19:18 UTC, dcdacosta commented on source/documentation/virtual_machine_management_guide/chap-Additional_Configuration.adoc
> +//:vmm:  this attribute seems to be messing up the compilation - testing commenting it out - Eli Marcus
This was not causing the issue; Said added a step 3 with an example to the Configuring_Time_Zones.adoc and forgot to include the closing ---- for the example which read everything following it as part of the example. I have corrected the issue in https://github.com/oVirt/ovirt-site/pull/2679 and assigned you as a reviewer.

2022-01-05 19:19 UTC, dcdacosta requested changes
A few minor comments; otherwise, LGTM.

2022-01-06 14:29 UTC, RichardHoch approved these changes

2022-01-06 14:30 UTC, RichardHoch commented
LGTM!

2022-01-06 16:17 UTC, dcdacosta approved these changes

2022-01-06 16:17 UTC, merged