BZ2006228 - Updates for OVN/OVS upgrade to the Admin and Upgrade Guides
oVirt/ovirt-site pull request #2779
Opened 2022-03-14 22:49 UTC by dcdacosta

This PR is a duplicate of https://github.com/oVirt/ovirt-site/pull/2739. The admin guide changes were previously reviewed and approved. The main difference here is the update to the Upgrade Guide. I created a new PR based on merge conflict issue with original PR that I was unable to untangle. 

Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=2006228

Changes proposed in this pull request:
Fixes issue: https://bugzilla.redhat.com/show_bug.cgi?id=2006228
Changes proposed in this pull request:

Section 14.2.7: Removed CloudForms support note.
Section 14.2.7.1: Removed the warning about openvswitch version.
Section 14.2.7.2: Removed
Section 14.2.7.3: Removed
Section 14.2.7.4: Keep only the part under "Updating the OVN Tunnel Network on a Single Host", everything else can be removed.
The vdsm-tool snippet should be updated to:
vdsm-tool ovn-config OVN_Central_IP Tunneling_IP_or_Network_Name Host_FQDN
and example to:
vdsm-tool ovn-config 192.168.0.1 MyNetwork MyFQDN

Please add note under the first snippet: The Host_FQDN must match FQDN that is specified in engine for this host.

Section 14.2.8: Removed
Section 14.2.9, Table 14.1: Removed Type "OpenStack Networking".

Added upgrade notes to the Upgrade Considerations snippet in the Upgrade Guide.

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @dcdacosta

This pull request needs review by: @almusil

2022-03-15 05:58 UTC, almusil requested changes
Just a small phrasing change, other than that it looks good.

2022-03-15 05:58 UTC, almusil commented on source/documentation/common/upgrade/snip-upgrade_considerations.adoc
> +To verify whether the provider and OVN were configured successfully on the host, check the *OVN configured* flag on the *General* tab for the host. If the host's OVN is not confiugred, you can config
The last sentence seems wrong, you don't need to reinstall the engine, just the host from engine version 4.5 or higher. Does that make sense?

2022-03-21 15:00 UTC, emarcusRH commented on source/documentation/common/upgrade/snip-upgrade_considerations.adoc
> +** The engine must be upgraded first.
change "must be" to "is" to align with "as long as the following conditions are met"

2022-03-21 15:01 UTC, emarcusRH commented
/lgtm 
aside from minor wording change

2022-03-22 06:56 UTC, almusil commented on source/documentation/common/upgrade/snip-upgrade_considerations.adoc
> +To verify whether the provider and OVN were configured successfully on the host, check the *OVN configured* flag on the *General* tab for the host. If the host's OVN is not confiugred, you can config
One more thing, can you please add `If the *OVN Configured* is *No* try to refresh capabilites first` after the sentence?

2022-03-27 08:50 UTC, mburman5 commented on source/documentation/common/upgrade/snip-upgrade_considerations.adoc
> +
I would use the doc text from the RFE bug:
Upgrade from OvS/OVN 2.11 to OVN 2021 and OvS 2.15.

The upgrade is transparent to user as long as few conditions are met:

1) The engine must be upgraded first.
2) Before any host upgrade the ovirt-provider-ovn security groups must be disabled for all OVN networks that are expected to work between host with OVN/OvS version 2.11.
3) Upgrade hosts to match the OVN version 2021 or higher and OvS version to 2.15. This step should be done via the UI, in order to reconfigure OVN and refresh certificates.
4) Reboot the host after upgrade


To check if provider and OVN was configured successfully on the host, webadmin includes OVN configured flag in General tab for every host, at the same time this value is available via REST API. Please note that this value might say "No" until capabilities are refreshed for the host.

Fixing the host's OVN not being configured can be done by reinstalling it from engine 4.5 or higher.

2022-03-30 07:31 UTC, mburman5 commented on source/documentation/common/upgrade/snip-upgrade_considerations.adoc
> +
Looks goof to me. Small note, maybe it's worth to highlight that the host upgrade via the web admin portal is a MUST step in order the ovn and certificates properly reconfigured.

Thank you

2022-03-30 13:24 UTC, emarcusRH commented on source/documentation/common/upgrade/snip-upgrade_considerations.adoc
> +** The engine is upgraded first.
"the {engine name} is upgraded first" if this applies both upstream and downstream, or "Manager" for downstream only

2022-03-30 15:12 UTC, emarcusRH approved these changes
/lgtm overall
need to replace term "engine" with Manager in Upgrade Considerations topic

2022-04-27 18:29 UTC, merged