Update users-and-providers.md
oVirt/ovirt-site pull request #3167
Opened 2024-02-16 16:16 UTC by andresmmujica

Add SEAQ to Professional Services & Integrators segment

[Feature]

Changes proposed in this pull request:

- Adding new vendor to Professional Services & Integrators segment.

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): (@andresmmujica)

This pull request needs review by: @bproffitt  @sandrobonazzola

2024-02-16 16:22 UTC, sandrobonazzola requested changes

2024-02-16 16:22 UTC, sandrobonazzola commented on source/community/user-stories/users-and-providers.md
> +[![SEAQ](/wp-content/uploads/2022/07/LOGO-SEAQ-cropped-transparent.png)](https://seaq.us/)
This link to the logo is going to resolve to 404 error as it's a relative link

2024-02-16 16:22 UTC, sandrobonazzola commented on source/community/user-stories/users-and-providers.md
> +[SEAQ](https://seaq.us/) specializes in seamless transitions to oVirt for LATAM and USA businesses, offering deep virtualization expertise to navigate away from other vendors and embrace the technolo
the website doesn't mention anything related to oVirt

2024-02-25 06:05 UTC, gocallag commented
I tested the change via the procedure at https://github.com/oVirt/ovirt-site/blob/2ebfb790c06d2ee172fef351536ffa78772ea0d2/CONTRIBUTING.md and it looks ok to me :-)

2024-06-05 07:58 UTC, sandrobonazzola commented
Closing due to inactivity

2024-06-05 07:58 UTC, closed without merging